name: 'Properties File Action'
description: 'Perform read and write operations on properties files.'
author: 'kurt-code'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-text'
  color: 'yellow'

inputs:
  file-path:
    description: 'The path to the properties file.'
    required: true
  keys:
    description: 'Comma-separated list of keys to read or write.'
    required: false
  operation:
    description: 'determines the operation to perform. Can be either read or write.'
    required: true
    default: 'read'
  key-value-pairs:
    description: 'JSON key value pairs to write to file. e.g. {"key1": "val1", "key2": "val2"}'
    required: false

runs:
  using: node20
  main: dist/index.js
